dev:
  build: .
  environment:
    - DISPLAY
  volumes:
    - /tmp/.X11-unix/:/tmp/.X11-unix
    - ~/.Xauthority:/root/.Xauthority
    - ~/wd:/root/wd/
    - ~/.ssh:/root/.ssh/:ro
  network_mode: "bridge"
  dns: 8.8.8.8
  stdin_open: true
  tty: true
